app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.ItemsView.as_view(), name='list'),
    path('create/', views.create_item, name='create'),
    path('archive/', views.archived_list, name='archive'),
    path('delete/<int:pk>', views.delete_item, name='delete'),
    path('mark_done/<int:pk>', views.mark_done, name='mark_done'),
]

myauth/urls.py
from django.urls import path, reverse_lazy
from . import views


app_name = 'myauth'

urlpatterns = [
    path("registration/", views.RegistrationView.as_view(), name="registration"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
]

todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/", include("myauth.urls")),
    path("", include("app.urls"))
]

app/models.py
from django.db import models

from myauth.models import User


class TodoItem(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    text = models.TextField(max_length=500)
    done = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)

    def __str__(self):
        return self.title

myauth/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import UserManager


class UserManager(BaseUserManager):
    def create_user(self, email, password=None):
        if not email:
            raise ValueError("Email is required")
        if not password:
            raise ValueError("Password is required")
        email = self.normalize_email(email)
        user = self.model(email=email)
        user.set_password(password)
        user.save()
        print("!!!!!!!!!!1")
        return user

    def create_superuser(self, email, password):
        if not email:
            raise ValueError("Email is required")
        if not password:
            raise ValueError("Password is required")
        user = self.create_user(email, password)
        user.is_superuser = True
        user.is_staff = True
        user.save()
        return user


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    # username = models.CharField(max_length=50, unique=False)
    username = None
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    # REQUIRED_FIELDS = ['username']
    objects = UserManager()
    def __str__(self):
        return self.email

app/forms.py
from django.forms import ModelForm
from .models import TodoItem

class TodoForm(ModelForm):

    class Meta:
        model = TodoItem
        fields = ('title', 'text',)

    def __init__(self, *args, **kwargs):
        super(TodoForm, self).__init__(*args, **kwargs)
        self.fields['text'].required = False

myauth/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from myauth.models import User


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(label='email')

    class Meta:
        model = User
        fields = ('email',)

# class LoginForm(forms.ModelForm):
#     class Meta:
#
#         model = User
#         fields = ('email', 'password')

app/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views.generic import ListView, CreateView, DeleteView
from .models import TodoItem
from .forms import TodoForm

class LoginRequiredMixin(LoginRequiredMixin):
    login_url = "/auth/login"

@login_required(login_url='/auth/login/')
def home(request):
    return render(request, 'app/home.html')


class ItemsView(LoginRequiredMixin, ListView):
    template_name = 'app/item-list.html'
    context_object_name = 'items'

    # queryset = TodoItem.objects.filter(archived=False, author_id=request.user).order_by("-id")

    def get_queryset(self):
        return TodoItem.objects.filter(author=self.request.user, archived=False).order_by("-id")

# class CreateItemView(CreateView):
#     model = TodoItem
#     form_class = TodoForm
#     template_name = 'app/item-list.html'
#     fields = ('title', 'text', )
#     context_object_name = 'create_form'

def create_item(request):
    if request.method == 'POST':
        form = TodoForm(request.POST)
        if form.is_valid():
            item = form.save(commit=False)
            item.author = request.user
            item.save()
    else:
        form = TodoForm()
    items = TodoItem.objects.filter(author=request.user, archived=False).order_by('-id')
    return render(request, 'app/list_elem.html', {"create_form": form, "items": items})


class DeleteItemView(DeleteView):
    model = TodoItem
    template_name = 'app/item-list.html'
    success_url = 'app/list_elem.html'

def delete_item(request, pk):
    item = TodoItem.objects.get(id=pk)
    item.archived = True
    item.save()
    items = TodoItem.objects.filter(author=request.user, archived=False).order_by('-id')
    return render(request, 'app/list_elem.html', {'items': items})

def mark_done(request, pk):
    item = TodoItem.objects.get(id=pk)
    item.done = True
    item.save()
    items = TodoItem.objects.filter(author=request.user, archived=False).order_by('-id')
    return render(request, 'app/list_elem.html', {'items': items})

def archived_list(request):
    items = TodoItem.objects.filter(author=request.user, archived=True).order_by('-id')

    return render(request, 'app/archive.html', {'items': items})

myauth/views.py
from django import forms
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from .forms import CustomUserCreationForm



class RegistrationView(CreateView):
    # model = User
    form_class = CustomUserCreationForm
    # fields = ['email', 'username', 'password']
    success_url = reverse_lazy("myauth:login")
    template_name = "myauth/registration.html"


class LoginView(LoginView):
    template_name = "myauth/login.html"
    # form_class = LoginForm
    # success_url = reverse_lazy("app:list")


class LogoutView(LogoutView):
    template_name = "myauth/logout.html"

templates/app/archive.html
{% extends "base.html" %}

{% block title %}
	Archived
{% endblock %}


{% block body %}
    

    <ul class="item-list">
        {% for item in items %}
            <li class="todo-item">
                {{ item.title }}
                <p>{{ item.text }}</p>
                
            </li>


        {% endfor %}

    </ul>

    



    <script src="https://unpkg.com/htmx.org@1.9.2" integrity="sha384-L6OqL9pRWyyFU3+/bjdSri+iIphTN/bvYyM37tICVyOJkWZLpP2vGn6VUEXgzg6h" crossorigin="anonymous"></script>

    <script>
    document.body.addEventListener('htmx:configRequest', (event) => {
        event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
    })
    </script>
{% endblock %}

templates/app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>

<h1>Todo app</h1>

{% block body %}
	
{% endblock %}


</body>
</html>

templates/app/home.html
{% extends "base.html" %}

{% block title %}
	Home
{% endblock %}

{% block body %}

{% endblock %}

templates/app/item-list.html
{% extends "base.html" %}

{% block title %}
	Todo list
{% endblock %}

{% block body %}
    <div class="container">
    <form class="form" hx-post="{% url 'app:create' %}" hx-target="#items">
        {% csrf_token %}
        <input type="text" name="title" placeholder="Название">
        <input type="text" name="text" placeholder="Описание">
        <button type="submit" class="btn btn-outline-primary">Добавить</button>
    </form>
    </div>



    
    <div id="items">
        {% if items %}
            {% include 'app/list_elem.html' %}
        {% else %}
            <span style="margin: auto">У вас нет заданий</span>
        {% endif %}
    </div>
    



    <script src="https://unpkg.com/htmx.org@1.9.2" integrity="sha384-L6OqL9pRWyyFU3+/bjdSri+iIphTN/bvYyM37tICVyOJkWZLpP2vGn6VUEXgzg6h" crossorigin="anonymous"></script>

    <script>
    document.body.addEventListener('htmx:configRequest', (event) => {
        event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
    })
    </script>
{% endblock %}

templates/app/list_elem.html
<ul class="item-list">
            {% for item in items %}
                <li class="todo-item">
                {{ item.title }}
                <p>{{ item.text }}</p>
                {% if item.done %}
                	<p style="color: green">Статус: выполенено</p>
                {% else %}
                    <p style="color: red">Статус: не выполенено</p>
                {% endif %}
                
                {% if not item.done %}
                	<span hx-post="{% url 'app:mark_done' item.pk %}"
                  hx-target="#items" style="cursor: pointer">Пометить выполненным</span>
                    <br>
                {% endif %} 
                    
                <span hx-post="{% url 'app:delete' item.pk %}"
                  hx-target="#items" style="cursor: pointer;">Удалить</span>
                </li>


            {% endfor %}

            </ul>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body class="text-center">

<div class="container">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
      <a style="font-size: 35px" href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
        Todo
      </a>

      <div style="width: auto" class="col-md-3 text-end">

        {% if request.user.is_authenticated %}
            <form method="POST" action="{% url 'app:archive' %}" style="display: inline-block">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary me-2" >Архив</button>
            </form>
            
            <form method="POST" action="{% url 'myauth:logout' %}" style="display: inline-block">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary" >Выйти</button>
            </form>
        {% else %}
            <form action="{% url 'myauth:login' %}" style="display: inline-block;">
                <button type="submit" class="btn btn-outline-primary me-2" data-href-template="{">Войти</button>
            </form>
            <form action="{% url 'myauth:registration' %}" style="display: inline-block;">
                <button type="submit" class="btn btn-primary" >Зарегистрироваться</button>
            </form>

        {% endif %}
      </div>
    </header>
</div>

{% block body %}
	
{% endblock %}







<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>
</html>

templates/myauth/login.html
{% extends "base.html" %}

{% block title %}
    Войти
{% endblock %}

{% block body %}
    <div class="container" style="display: flex;justify-content: center;flex-direction: column">
    <h2>Войти</h2>
    <form class="form" method="POST">

            {% csrf_token %}
{#            {{ form.as_p }}#}
            <span>Введите email</span>
            <div class="label_username">{{ form.username }}</div>
            <span>Введите пароль</span>
            {{ form.password }}
            <button type="submit" class="btn btn-outline-primary">Login</button>

    </form>
    </div>
{% endblock %}

templates/myauth/logout.html
{% extends "base.html" %}

{% block title %}
    Logout
{% endblock %}

{% block body %}
	<h2>Выйти</h2>
    <a href="{% url 'myauth:login' %}">Войти</a>
{% endblock %}

templates/myauth/registration.html
{% extends "base.html" %}

{% block title %}
    Registration
{% endblock %}

{% block body %}
	<h2>Registration</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Sign up</button>
    </form>
{% endblock %}